### ISSUE TITLE
Add capability to edit ticket titles

### ISSUE THREAD

**Issue by JBL132** [QIntegration/Qualys-Jira-Connector#5]
Currently the connector will submit the Jira ticket as follows.
Host Title: "Qualys host ID <ID Value>"
Vulnerability Title: Qualys QUID <ID Value> found.
Our reason for using the connector is to create a process around remediation. Currently, the team working the tickets would need to open and review every ticket to understand what the host/vulnerability is. Adding vulnerability name and host name to the titles of the tickets would help the end user better understand the ticket without having to open and review the ticket details.

**Comment by JimReprogle** [comment]
You should be able to accomplish this by editing the `Host_Vuln_Linking_Ticket_Scheme.json` file.
It is located in the docker volume as described by the `docker-compose.yml` file.
![image](https://github.com/QIntegration/Qualys-Jira-Connector/assets/65737617/768e1468-38f9-40b9-ba3c-a57972d065aa)
